name: CI - Code Check

on: [push, pull_request]

jobs:
  code-check:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Check flutter sdk version
        run: flutter --version

      - name: Get dependencies
        run: flutter pub get

      - name: Run Code Generation
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Run custom_lint
        run: flutter analyze --fatal-infos

      - name: Setup Dart Code Metrics
        run: dart pub get dart_code_metrics

      - name: Dart Code Metrics
        run: |
          dirs_to_analyze=""
          if [ -d lib ]; then dirs_to_analyze+=" lib"; fi
          if [ -d test ]; then dirs_to_analyze+=" test"; fi
          if [ -d example ]; then dirs_to_analyze+=" example"; fi

          if [ dirs_to_analyze != "" ]
          then
            dart run dart_code_metrics:metrics \
              analyze \
              $dirs_to_analyze \
              --fatal-warnings \
              --fatal-performance \
              --fatal-style
            dart run dart_code_metrics:metrics \
              check-unused-files \
              $dirs_to_analyze \
              --fatal-unused
            dart run dart_code_metrics:metrics \
              check-unused-code \ 
              $dirs_to_analyze \
              --fatal-unused
          fi

      - name: Check formatting
        run: dart format . --set-exit-if-changed

      - name: Run Tests
        run: |
          if [ -d test ]; then
            flutter test --reporter=expanded
          else
            echo "Tests not found."
          fi
